name: async_await
description: Compile-time support for "async/await" syntax in Dart.
dependencies:
  analyzer: '>=0.22.4 <0.23.0'
  barback: '>=0.15.0 <0.16.0'
dev_dependencies:
  http: any
  unittest: any
